# Generated by Django 3.2.7 on 2021-10-19 09:09

from django.db import migrations, models
import django.db.models.deletion
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.user'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='img',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to=tours.models.user_directory_path),
        ),
    ]
